# Generated by Django 5.1.3 on 2024-12-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("german_word", models.CharField(max_length=50)),
                ("farsi_word", models.CharField(max_length=50)),
                (
                    "english_word",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("definition", models.TextField()),
                ("german_example_sentence", models.TextField()),
                ("farsi_example_sentence", models.TextField(blank=True, null=True)),
                ("english_example_sentence", models.TextField(blank=True, null=True)),
                ("synonyms", models.TextField(blank=True, null=True)),
                ("antonyms", models.TextField(blank=True, null=True)),
                ("audio", models.FileField(blank=True, null=True, upload_to="audio/")),
                (
                    "german_example_audio",
                    models.FileField(
                        blank=True, null=True, upload_to="german_example_audio/"
                    ),
                ),
                (
                    "english_example_audio",
                    models.FileField(
                        blank=True, null=True, upload_to="english_example_audio/"
                    ),
                ),
                (
                    "english_audio",
                    models.FileField(blank=True, null=True, upload_to="english_audio/"),
                ),
                ("video", models.FileField(blank=True, null=True, upload_to="videos/")),
            ],
        ),
    ]
