# Generated by Django 5.1.3 on 2024-12-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("m", "Masculine"), ("f", "Feminine"), ("n", "Neutral")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="word",
            name="genitive_form",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="word",
            name="is_noun",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="word",
            name="is_verb",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="word",
            name="past_perfect",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="word",
            name="plural_form",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="word",
            name="simple_past",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="word",
            name="subjunctive",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
