# Generated by Django 5.1.3 on 2024-12-08 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0002_word_gender_word_genitive_form_word_is_noun_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="word",
            old_name="past_perfect",
            new_name="auxiliary_verb",
        ),
        migrations.RenameField(
            model_name="word",
            old_name="subjunctive",
            new_name="past_participle",
        ),
    ]
