# Generated by Django 5.1.3 on 2024-12-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0003_rename_past_perfect_word_auxiliary_verb_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="comparative",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="word",
            name="superlative",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="word",
            name="word_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("noun", "Nomen"),
                    ("verb", "Verb"),
                    ("adjective", "Adjektiv"),
                    ("article", "Artikel"),
                    ("pronoun", "Pronomen"),
                    ("numeral", "Numerale"),
                    ("adverb", "Adverb"),
                    ("preposition", "Präposition"),
                    ("conjunction", "Konjunktion"),
                    ("interjection", "Interjektion"),
                    ("particle", "Partikel"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
