# Generated by Django 5.1.3 on 2025-01-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0005_flashcard"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="usage",
            field=models.TextField(blank=True, null=True),
        ),
    ]
